# Generated by Django 6.0.6 on 2026-06-25 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
        ('students', '0004_student_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('mentee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='peer_mentor', to='students.student')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_mentees', to='students.student')),
            ],
            options={
                'ordering': ['mentor', 'mentee'],
            },
        ),
    ]
