# Generated by Django 6.0.6 on 2026-06-22 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('cultural', 'Cultural'), ('sports', 'Sports'), ('technical', 'Technical'), ('workshop', 'Workshop'), ('seminar', 'Seminar')], default='academic', max_length=20)),
                ('is_upcoming', models.BooleanField(default=True)),
                ('registration_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
