# Generated by Django 6.0.5 on 2026-06-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='guardian_name',
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
