services:
  - type: web
    name: student-management-system
    runtime: python
    plan: free
    buildCommand: './build.sh'
    startCommand: 'bash start.sh'
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: student_management.settings
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: 'False'
      - key: DJANGO_ALLOWED_HOSTS
        value: '.onrender.com,127.0.0.1,localhost'
      - key: DATABASE_URL
        value: postgresql://postgres:Adbhutpatel%402007@db.iqhhekuprbaotdwfkqul.supabase.co:5432/postgres?sslmode=require
      - key: DJANGO_EMAIL_BACKEND
        value: django.core.mail.backends.console.EmailBackend
