services:
  - type: web
    name: student-management-system
    runtime: python
    plan: free
    buildCommand: './build.sh'
    startCommand: 'gunicorn student_management.wsgi --preload --workers 4 --timeout 120 --access-logfile - --error-logfile -'
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: student_management.settings
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: 'False'
      - key: DJANGO_ALLOWED_HOSTS
        value: '.onrender.com,127.0.0.1,localhost'
      - key: DATABASE_URL
        value: postgresql://miracle_3wkm_user:wtLZe3I8LpJMplRlFG41o0lHxB7IXLiR@dpg-d8sophcm0tmc73aqf3dg-a.virginia-postgres.render.com/miracle_3wkm
      - key: DJANGO_EMAIL_BACKEND
        value: django.core.mail.backends.console.EmailBackend
