# Generated by Django 6.0.6 on 2026-06-23 19:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_remove_student_guardian_name_student_father_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., President, Vice President, Secretary', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('max_winners', models.IntegerField(default=1, help_text='Number of winners for this position')),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('positions', models.ManyToManyField(related_name='elections', to='elections.position')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifesto', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='elections/candidates/')),
                ('is_approved', models.BooleanField(default=False)),
                ('nomination_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('vote_count', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidacies', to='students.student')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.election')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.position')),
            ],
            options={
                'ordering': ['position', 'student'],
                'unique_together': {('student', 'election', 'position')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='elections.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='elections.election')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.position')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='students.student')),
            ],
            options={
                'verbose_name_plural': 'Votes',
                'unique_together': {('student', 'election', 'position')},
            },
        ),
    ]
