# Generated by Django 6.0.6 on 2026-06-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_leadershipmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='director/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Director's Message",
                'verbose_name_plural': "Director's Messages",
            },
        ),
    ]
