# Generated by Django 6.0.6 on 2026-06-23 13:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_remove_student_guardian_name_student_father_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntiRaggingCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(help_text='e.g., Chairman, Member', max_length=200)),
                ('role', models.CharField(help_text='e.g., Professor, HOD', max_length=200)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(blank=True, upload_to='antiragging/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Anti-Ragging Committee Member',
                'verbose_name_plural': 'Anti-Ragging Committee',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AntiRaggingComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ragging', 'Ragging Incident'), ('harassment', 'Harassment'), ('discrimination', 'Discrimination'), ('other', 'Other')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('admin_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='antiragging_complaints', to='students.student')),
            ],
            options={
                'verbose_name': 'Anti-Ragging Complaint',
                'verbose_name_plural': 'Anti-Ragging Complaints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AntiRaggingUndertaking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_date', models.DateField(auto_now_add=True)),
                ('uploaded_file', models.FileField(blank=True, help_text='Upload signed undertaking (PDF/Image)', upload_to='antiragging/undertakings/')),
                ('is_accepted', models.BooleanField(default=False)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antiragging_undertaking', to='students.student')),
            ],
        ),
    ]
