# Generated by Django 6.0.6 on 2026-06-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_clubapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubapplication',
            name='email',
            field=models.EmailField(blank=True, help_text='Student email for contact', max_length=254),
        ),
    ]
