# Generated by Django 6.0.6 on 2026-06-22 18:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_clubapplication_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(help_text='e.g. Chief Coordinator, Faculty Coordinator', max_length=200)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message='Enter a valid phone number')])),
                ('photo', models.ImageField(blank=True, upload_to='coordinators/')),
                ('is_chief', models.BooleanField(default=False, help_text='Chief Coordinator / Head of the cell')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinators', to='clubs.club')),
            ],
            options={
                'ordering': ['cell', '-is_chief', 'order', 'name'],
            },
        ),
    ]
