# Generated by Django 6.0.6 on 2026-06-23 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_cellcoordinator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubapplication',
            name='email',
        ),
    ]
