# Generated by Django 6.0.6 on 2026-06-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_remove_clubapplication_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubapplication',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Verify your date of birth', null=True),
        ),
    ]
